1. 启动mysql

问题：碰到无法找到某个对象的问题，删除table然后重新create_all()搞定

from __init__ import db
from models import *
db.create_all()
admin = User('admin', 'jf0t!s298')
db.session.add(admin)
db.session.commit()

user
user1 = User('huangli', 'converse')
user1 = User('admin', 'u9ec4u7acb')
db.session.add(user1)
db.session.commit()

community
c1 = Community('景秀天下', user1.id)
db.session.add(c1)
db.session.commit()

search
user1 = db.session.query(User).filter_by(username='ekinasm').first()
user1.community
user1.community.name 报错，为什么可以找到community对象，但是无法引用字段了？

快递收存单
# box_number:箱柜编号
# company：快递公司
# phone：客户电话
# name：客户姓名
# delivery_time:送达时间
# pick_time:取件时间
# community_id: 小区id
from datetime import datetime
c1 = db.session.query(Community).first()
d1 = datetime.today()
d2 = datetime.today()
receipt1 = Receipt('A0012312','box05','顺风','18671755701','黄立',d1,d2,c1.id)
db.session.add(receipt1)
db.session.commit()
#如何获取3个月数据
t1 = Receipt.query.filter()

发件单
c1 = db.session.query(Community).first()
from datetime import datetime
d1 = datetime.today()
post1 = Post('S0012312','顺风','18671755701','冉凤鸣',d1,18,c1.id)
db.session.add(post1)
db.session.commit()

#search
user1 = User.query.filter_by(name='huangli').first()
use2 =User.query.filter_by(name='huangli').filter_by(password='converse').first()

#role
roleadmin = Role(name='admin',description = 'Administrator')
roleuser = Role(name = 'user',description =  'end user')
db.session.add(roleadmin)
db.session.add(roleuser)
db.session.commit()
